% Run this script at the start of a MATLAB session to set default values, etc.
set(groot, 'defaultFigureColor', 'white', 'defaultTextInterpreter', 'latex', ...
'defaultLegendInterpreter', 'latex', 'defaultAxesTickLabelInterpreter', 'latex', ...
'defaultTextFontSize', 12, 'defaultAxesLabelFontSizeMultiplier', 1.5, ...
'defaultTextHorizontalAlignment', 'center', 'defaultAxesLineWidth', 1.5, ...
'defaultAxesFontSize', 12, 'defaultAxesTitleFontSizeMultiplier', 1.5)
